### ISSUE TITLE
Error when trying to parse result of __toXML()

### ISSUE THREAD

**Issue by chekalsky** [mhor/php-mediainfo#116]
After I got `MediaInfoContainer` I am trying to store result into DB to be able to restore state later.

```php
$mediaInfo = new MediaInfo();
$info = $mediaInfo->getInfo($url);

var_dump($info->getGeneral()); // all right

$xml = (string) $this->container->__toXML()->asXML();
```

The I try to restore the state:

```php
$mediaInfoOutputParser = new MediaInfoOutputParser();
$mediaInfoOutputParser->parse($xml);
```

Getting such warning: `Warning: simplexml_load_string(): Entity: line 2: parser error : Opening and ending tag mismatch: MediaInfoContainer line 2 and codec_id`

Because of the such part:
```xml
...
<internet_media_type>video/mp4</internet_media_type>
 <codec_id>
    <0>qt  </0>
    <1>qt   0000.02 (qt  )</1>
</codec_id>
<codec_id_url>http://www.apple.com/quicktime/download/standalone.html</codec_id_url>
...

```

**Comment by mhor** [comment]
@chekalsky the xml serialization was fix and released as [5.3.1](https://github.com/mhor/php-mediainfo/releases/tag/5.4.1)
