### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by alangregory** [mhor/php-mediainfo#42]
###### Filenames with characters like 'ç,^' works nice when using php cli, but fails when loading via webserver.
Example:
```
$mkv_file = 'Êxodo: Deuses e Reis (2014)/Êxodo: Deuses e Reis.mkv';
$mediaInfo = new MediaInfo();
$mediaInfoContainer = $mediaInfo->getInfo($mkv_file);
var_dump($mediaInfoContainer);
```

**Comment by mhor** [comment]
Thanks for issues reporting this issue @alangregory , I will try to solve this, quickly.
Witch OS do you use?

**Comment by alangregory** [comment]
##### Ubuntu Server 14.04.3 LTS
###### php -v 
```
PHP 5.6.16-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by alangregory** [comment]
in MediaInfoCommandRunner.php function run
works using Process instead of Process Building

**Comment by mhor** [comment]
@alangregory could it be closed?

**Comment by alangregory** [comment]
Yes, you can close, it's working now.
