### ISSUE TITLE
Warning: escapeshellarg() expects parameter 1 to be string, array given (...)

### ISSUE THREAD

**Issue by YohannLYD** [mhor/php-mediainfo#45]
I am running into this error when I am trying to fetch information from a media.

	ContextErrorException: Warning: escapeshellarg() expects parameter 1 to be string, array given in /Applications/MAMP/htdocs/playerAV/vendor/symfony/symfony/src/Symfony/Component/Process/ProcessUtils.php line 74

Here is my controller action code :

	public function testMediaAction(){
	
		$mediaInfo = new MediaInfo();
		$repository = $this->getDoctrine()
                           ->getManager()
                           ->getRepository('PlayerBundle:Player\Media');
                           
		$media = $repository->findOneBy(array('id' => '5'));
		$fichier = $media->getWebPath();

		$general = $mediaInfo->getInfo($fichier)->getGeneral();
		return $this->render('PlayerBundle:Player:Media/test.html.twig', array('general' => $general));
	}

I can't find the part where I am doing something wrong. Any idea where the issue comes from ?
I am using Symfony 2.3, MediaInfo v0.7.77 (installed on Mac OS X via homebrew) and running my server locally with MAMP.

**Comment by mhor** [comment]
Thanks for issue reporting @YohannLYD.

What is the value of $fichier?

**Comment by YohannLYD** [comment]
The value of $fichier returns the path to the media file ("uploads/film.mp4" in my case).

**Comment by mhor** [comment]
@YohannLYD Could you tell me if #46 fix the bug

**Comment by YohannLYD** [comment]
@mhor unfortunaltely it doesn't, I run into a  "sh: mediainfo: command not found" error when I make the changes to MediaInfoCommandRunner.php

**Comment by mhor** [comment]
@YohannLYD ``mediainfo`` doesn't exist, it's probably not the right command to run mediainfo. Wich command did you use to run mediainfo on cli?

**Comment by YohannLYD** [comment]
Hi @mhor,

On the cli, both "mediainfo" and "/usr/local/bin/mediainfo" can run the command.
I made a slight change on MediaInfoCommandRunner.php which made the bundle work.
If I change the line
```php
protected $command = 'mediainfo';
```
by the absolute path of the binary (/usr/local/bin/mediainfo in my case)
```php
protected $command = '/usr/local/bin/mediainfo';
```

I can properly get the information of my media.

It's kind of good for me this way, but I am not sure about how to make the bundle work just by providing "mediainfo" instead its full path.

**Comment by mhor** [comment]
@YohannLYD IMO the ``command`` property should be configurable like:

```php
$mediaInfo = new MediaInfo();
$mediaInfo->setConfig('command', '/usr/local/bin/mediainfo');
$mediaInfoContainer = $mediaInfo->getInfo('music.mp3');
```

**Comment by YohannLYD** [comment]
@mhor it works now. I ran into another error but you can see #47 for my suggestions.

**Comment by mhor** [comment]
Ok @YohannLYD I close this issue
