### ISSUE TITLE
Remote file Support

### ISSUE THREAD

**Issue by tim-hanssen** [mhor/php-mediainfo#55]
Would it be possible to add remote file support to the libary?
Mediainfo supports native AWS S3 files. But from the libary I get a error "File doesn't exist ".

Commeting out the file exist check in de MediaInfoCommandBuilder gets the job done for now

**Comment by mhor** [comment]
@tim-hanssen released a [2.2.0](https://github.com/mhor/php-mediainfo/releases/tag/2.2.0)
