### ISSUE TITLE
use url for path to media file

### ISSUE THREAD

**Issue by scottf-tvw** [mhor/php-mediainfo#59]
supported? if so config example
TY

**Comment by mhor** [comment]
@scottf-tvw Yes it is, done in https://github.com/mhor/php-mediainfo/pull/56 release as [2.2.0](https://github.com/mhor/php-mediainfo/releases/tag/2.2.0)

**Comment by scottf-tvw** [comment]
The latest pull from composer, it failed for me. Are there any config parameters to consider or to send to the class?

**Comment by mhor** [comment]
Could you give me the required version of "mhor/php-mediainfo" into ``composer.json``? 

This code should work
```php
$mediaInfo = new MediaInfo();
$mediaInfoContainer = $mediaInfo->getInfo('http://example.org/music/test.mp3');
```

**Comment by scottf-tvw** [comment]
I used *.

**Comment by mhor** [comment]
@scottf-tvw ok, could you give an example of code which does not work

**Comment by mhor** [comment]
Closed for now, can't be reproduced
