### ISSUE TITLE
How to use on windows IIS7 PHP

### ISSUE THREAD

**Issue by WeBBLiu** [mhor/php-mediainfo#73]
How to use on windows IIS7 PHP 
Thanks.

**Comment by Nek-** [comment]
Hello,

I guess no one used this on windows. Be the first, be the warrior and do not hesitate to provide a documentation pull-request !

![](https://media.giphy.com/media/l2YWE2ZXqiYa4h8ic/giphy.gif)

**Comment by elfen** [comment]
:1st_place_medal:

**Comment by mhor** [comment]
@cklm cr
