### ISSUE TITLE
Mediainfo >= 17.10 changed XML Format

### ISSUE THREAD

**Issue by franzfroemel** [mhor/php-mediainfo#82]
https://mediaarea.net/MediaInfo/ChangeLog / Version 17.10, 2017-11-02

> + New MediaInfo XML output, with XSD, more suitable for automatic parsing. Use Option("Inform", "OLDXML") for keeping previous behavior

Quick and Dirty solution -> change in Runner\MediaInfoCommandRunner.php
-    `protected $arguments = ['--OUTPUT=XML', '-f'];`
+   `protected $arguments = ['--OUTPUT=OLDXML', '-f'];`

**Comment by mhor** [comment]
@franzfroemel this is a duplicate of #76
