### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by meyer59** [mhor/php-mediainfo#85]
Hi,
Could be great to have the dependency updated to be compatible with Laravel 5.6
Error: 
`Conclusion: don't install symfony/process v4.0.2
    - mhor/php-mediainfo 3.0.0 requires symfony/process ~2.3|~3.0 `
Thank you!

**Comment by mhor** [comment]
@meyer59 Support of symfony component >= 4.0.0 was added on version 4.* of php-mediainfo see [Packagist](https://packagist.org/packages/mhor/php-mediainfo#4.0.2). 
Related to https://github.com/mhor/php-mediainfo/issues/77
