### ISSUE TITLE
sh: 1: mediainfo: not found

### ISSUE THREAD

**Issue by ashishranpara** [mhor/php-mediainfo#90]
Hello Sir/Medam,

I am getting below error on .3gp file.
**sh: 1: mediainfo: not found**

Please help me for the same.
Thanks

**Comment by radhanpuraankit** [comment]
Hello,
I am facing same issue on behat. Please give your help/suggestion for the same.

**Comment by mhor** [comment]
Hi @ashishranpara @radhanpuraankit did you install [mediainfo](https://mediaarea.net/en/MediaInfo/Download) as explained [here](https://github.com/mhor/php-mediainfo#1---install-mediainfo) ? php-mediainfo run and parse mediainfo command output if mediainfo is not installed php-mediainfo can't work. You can also specify the command to execute (see [here](https://github.com/mhor/php-mediainfo#extra)). For an installation on Windows see [here](https://github.com/mhor/php-mediainfo#usage-for-windowsos).

PS: sorry for response time.

**Comment by davecgs** [comment]
OK, question. I want to have the library off of a relative path vs. a path below the php code. 

Meaning, in my case, I want to treat this library as shared library among the website applications.
Exact request.

Instead of PA2/vendor/..

to ../LIB/vendor/..

Can I do that?

**Comment by davecgs** [comment]
For those having trouble, remember that the library is installed as a relative path. What that means is, depending on where your directory structure is, it will install.  If you are in the path:
\bob   it will install \bob\vendor   ....etc

If your website is somewhere else, it will NEVER find that code. Hope that helps.

**Comment by mhor** [comment]
@davecgs Thanks for your question if your problem is solved I will close this issue as there was no feedback from @radhanpuraankit & @ashishranpara.

If you have question do not hesitate to open another issues.

**Comment by hassanazimi** [comment]
@mhor I think it would have been nice to configure the path for where the mediainfo binary is in your package, something like FFMPEG / FFPROBE. if there is please let me know.

**Comment by hassanazimi** [comment]
I found how to configure the path of the binary

```
(new \Mhor\MediaInfo\MediaInfo)->setConfig('command', '/opt/homebrew/bin/mediainfo');
```
