### ISSUE TITLE
A way to save modified information

### ISSUE THREAD

**Issue by darki73** [mhor/php-mediainfo#91]
So the question is pretty much in the title of this issue.

Is there a way to save information to the opened file?

For example, i have a library of 50 mkv files, and i know that each of them has 2 audio tracks, first track is for Russian language and second one is for English, however, these tracks are not 'labeled', so there is no 'language' attribute present on the `Audio` class.

The following piece of code is used to add missing feature to the audio track:
```
$locales = [
        0   =>  [
            'ru',
            'Russian',
            'Russian',
            'ru',
            'rus',
            'ru'
        ],
        1   =>  [
            'en',
            'English',
            'English',
            'en',
            'eng',
            'en',
        ]
    ];

    /**
     * @var \Mhor\MediaInfo\Type\Audio $audio
     */
    foreach ($mediaInfoContainer->getAudios() as $index => $audio) {
        $audio->set('language', $locales[$index]);
    }
```

So, back to the question again, how can i write back the updated information?

**P.S.** I know about duplicate array elements, however, just to be sure, i would like to leave them as they were read from the 'valid' file which was edited by my media player.

**Comment by mhor** [comment]
Hi @darki73 , php-mediainfo goal is to wrap [mediainfo](https://mediaarea.net/fr/MediaInfo) command line and unfortunately does not allow metadata tag editing. You should use another tool/lib to edit them.

I think ffmpeg can do this ([see](https://wiki.multimedia.cx/index.php?title=FFmpeg_Metadata)). You can use php lib [PHP-FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg) to wrap ffmpeg.

**Comment by mhor** [comment]
Closed for now, considered as solved. If you have other question do not hesitate to open another issue.
