### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mhor** [mhor/php-mediainfo#96]
- [x] phpunit (PR #95)
- [x] symfony/process (PR https://github.com/mhor/php-mediainfo/pull/108)
- [x] symfony/filesystem

**Comment by ChangePlaces** [comment]
Can't use this with symfony 5 because of process dependency issues. Is there any particular reason why it's limited to process 4.*?

**Comment by mhor** [comment]
@ChangePlaces see this comment: https://github.com/mhor/php-mediainfo/pull/105#issuecomment-598437886 and this PR comment: https://github.com/mhor/php-mediainfo/pull/83#discussion_r167436812
